# Generated by Django 5.0.4 on 2024-04-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "paperpilot.authors",
            },
        ),
    ]
